### ISSUE TITLE
Module / Invalid paths

### ISSUE THREAD

**Issue by H-i-red** [nystudio107/generator-craftplugin#51]
![bug2](https://user-images.githubusercontent.com/19476159/35506031-4d2f7c62-04e8-11e8-8774-f46fe1790ca4.png)
![bug1](https://user-images.githubusercontent.com/19476159/35506032-4d4a526c-04e8-11e8-9696-2760057970d7.png)

**Comment by H-i-red** [comment]
I think it should be:
`'basePath' => '@modules/stylemodule/translations'`
not:
`'basePath' => '@stylemodule/translations'`

**Comment by H-i-red** [comment]
And this:
`$this->sourcePath = "@modules/stylemodule/assetbundles/stylemodule/dist";`
not:
`$this->sourcePath = "@stylemodule/assetbundles/stylemodule/dist";`

**Comment by codyjames** [comment]
Good call @H-i-red. That fixed an issue for me.

**Comment by khalwat** [comment]
Really strange. This is something I definitely fixed/changed in the last release, I'm not sure how it got reverted. I even generated a module with it, and go the correct code.

Anyway, it's been fixed in 1.4.2:

https://github.com/nystudio107/generator-craftplugin/releases/tag/1.4.2

This is also live up on https://pluginfactory.io/
